### ISSUE TITLE
Playback speed resets to 1.00 when entering/exiting fullscreen mode on YouTube

### ISSUE THREAD

**Issue by Julian1203** [codebicycle/videospeed#50]
I'm using Firefox.

**Comment by Kevin-Mok** [comment]
Apparently this is fixed in [the Chrome version](https://github.com/igrigorik/videospeed/pull/447) now.

**Comment by koloved** [comment]
is it possible to get this fix on Firefox?

**Comment by sloganking** [comment]
I'd like to take a shot at this issue but am new to extensions. If anyone could link a good resource showing how to set up a proper development environment, it would be much appreciated.

**Comment by sloganking** [comment]
Figured it out. Please see #68 for a fix.

**Comment by sloganking** [comment]
I am no longer experiencing this issue in the latest release. PR #45 which attempted to address this issue was also just closed as a result. @Julian1203 can you verify whether this is still affecting you and close the issue if it's not? 

If this is no longer an issue then I will close PR #68 which was my own attempt to fix this issue.

**Comment by Julian1203** [comment]
It's working for me. @SleepingFox88
